CREATE TABLE "artworks" (
	"Title"	TEXT,
	"Artist"	TEXT,
	"ConstituentID"	INTEGER,
	"ArtistBio"	TEXT,
	"Nationality"	TEXT,
	"BeginDate"	TEXT,
	"EndDate"	TEXT,
	"Gender"	TEXT,
	"Date"	TEXT,
	"Medium"	TEXT,
	"Dimensions"	TEXT,
	"CreditLine"	TEXT,
	"AccessionNumber"	TEXT,
	"Classification"	TEXT,
	"Department"	TEXT,
	"DateAcquired"	TEXT,
	"Cataloged"	TEXT,
	"ObjectID"	INTEGER NOT NULL UNIQUE,
	"URL"	TEXT,
	"ThumbnailURL"	TEXT,
	"Circumference (cm)"	REAL,
	"Depth (cm)"	REAL,
	"Diameter (cm)"	REAL,
	"Height (cm)"	REAL,
	"Length (cm)"	REAL,
	"Weight (kg)"	REAL,
	"Width (cm)"	REAL,
	"Seat Height (cm)"	REAL,
	"Duration (sec.)"	REAL,
	PRIMARY KEY("ObjectID" AUTOINCREMENT)
);

CREATE TABLE "artists" (
	"ConstituentID"	INTEGER NOT NULL UNIQUE,
	"DisplayName"	TEXT,
	"ArtistBio"	TEXT,
	"Nationality"	TEXT,
	"Gender"	TEXT,
	"BeginDate"	INTEGER,
	"EndDate"	INTEGER,
	"Wiki QID"	TEXT,
	"ULAN"	REAL,
	PRIMARY KEY("ConstituentID" AUTOINCREMENT)
);
